# FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-buster
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install extra tooling into the environment via the following command
RUN apt-get update && apt-get install vim
